version: '3.8'

services:
  mixa-backend:
    image: ghcr.io/syamban14/mixa-backend:latest
    container_name: mixa-backend
    expose:
      - "8000"
    networks:
      - mixa_net
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    restart: always
    environment:
      - TZ=Asia/Jakarta

  mixa-frontend:
    image: ghcr.io/syamban14/mixa-frontend:latest
    container_name: mixa-frontend
    ports:
      - "80:80"
    networks:
      - mixa_net
    restart: always
    depends_on:
      - mixa-backend

networks:
  mixa_net:
    driver: bridge
