version: '3.8'

services:
  mixa-backend:
    image: ghcr.io/syamban14/mixa-backend:latest
    container_name: mixa-backend
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./trading.db:/app/trading.db
    restart: always
    environment:
      - TZ=Asia/Jakarta

  mixa-frontend:
    image: ghcr.io/syamban14/mixa-frontend:latest
    container_name: mixa-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mixa-backend

